require:
  - rubocop/rspec/focused

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics:
  Enabled: false
RSpec/Focused:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/NilComparison:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 15
Style/NumericPredicate:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
