version: 2
executorType: docker
containerInfo:
  - image: ruby:2.3.3
stages:
  build:
    working_directory: /root/muffin
    steps:
      - type: checkout
      - type: cache-restore
        key: gemfile-{{ checksum "muffin.gemspec" }}
      - type: shell
        name: Install Ruby Dependencies
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - type: cache-save
        key: gemfile-{{ checksum "muffin.gemspec" }}
        paths:
          - vendor/bundle
      - type: shell
        name: Run Tests
        command: bundle exec rspec --format documentation
